[tool.black]
line-length = 120
target-version = ["py312"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 120
ignore = [
    "E203",  # Whitespace before ':', conflicts with black
    "W503"   # Line break before binary operator, conflicts with black
]
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "migrations",
    "instance",
    "frontend",
    "node_modules",
    "build",
    "static",
    "templates"
]
