"""Initial migration

Revision ID: 561c8d7816ce
Revises: 
Create Date: 2024-08-08 15:18:21.529831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561c8d7816ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10)))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.create_unique_constraint('uq_sets_code', ['code'])
        batch_op.drop_column('set_symbol')
        batch_op.drop_column('set_code')
        batch_op.drop_column('release_date')
        batch_op.drop_column('is_digital')
        batch_op.drop_column('set_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_digital', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('set_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('set_symbol', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('uq_sets_code', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('name')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
