"""Add Cache model

Revision ID: 23f77955d485
Revises: 
Create Date: 2024-07-01 16:49:27.089889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f77955d485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('magic_sets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_sets',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('set_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('set_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('set_symbol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('set_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('card_count', sa.INTEGER(), nullable=True),
    sa.Column('is_digital', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_name', 'set_code')
    )
    op.drop_table('cache')
    # ### end Alembic commands ###
