"""Changed Scan date to created_at

Revision ID: 39f9ded1a081
Revises: 0e4819adbdb2
Create Date: 2024-08-06 15:18:54.983123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f9ded1a081'
down_revision = '0e4819adbdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_sets')
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')

    op.create_table('_alembic_tmp_sets',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('set_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('card_count', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tcgplayer_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('uri', sa.VARCHAR(length=255), nullable=True),
    sa.Column('scryfall_uri', sa.VARCHAR(length=255), nullable=True),
    sa.Column('search_uri', sa.VARCHAR(length=255), nullable=True),
    sa.Column('released_at', sa.DATE(), nullable=True),
    sa.Column('printed_size', sa.INTEGER(), nullable=True),
    sa.Column('digital', sa.BOOLEAN(), nullable=True),
    sa.Column('nonfoil_only', sa.BOOLEAN(), nullable=True),
    sa.Column('foil_only', sa.BOOLEAN(), nullable=True),
    sa.Column('icon_svg_uri', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_sets_code')
    )
    # ### end Alembic commands ###
