"""empty message

Revision ID: 8a9ffe301bf5
Revises: 57d910cc867d
Create Date: 2024-11-19 16:21:26.648859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9ffe301bf5'
down_revision = '57d910cc867d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buylist_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buylist_card', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('version')
        batch_op.drop_column('language')
        batch_op.drop_column('set')

    # ### end Alembic commands ###
