"""Add CardData model and update ScanResult

Revision ID: 8b64deac896f
Revises: c38d676e0d0b
Create Date: 2024-07-03 13:06:36.547271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b64deac896f'
down_revision = 'c38d676e0d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('oracle_id', sa.String(length=255), nullable=False),
    sa.Column('multiverse_ids', sa.String(length=255), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('set_code', sa.String(length=10), nullable=True),
    sa.Column('set_name', sa.String(length=255), nullable=True),
    sa.Column('collector_number', sa.String(length=20), nullable=True),
    sa.Column('variation', sa.Boolean(), nullable=True),
    sa.Column('promo', sa.Boolean(), nullable=True),
    sa.Column('prices', sa.JSON(), nullable=True),
    sa.Column('purchase_uris', sa.JSON(), nullable=True),
    sa.Column('cardconduit_data', sa.JSON(), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_data')
    # ### end Alembic commands ###
