"""Remove Cache model to use LargeBinary

Revision ID: c38d676e0d0b
Revises: ed9dabb3e8d7
Create Date: 2024-07-01 16:59:43.773620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38d676e0d0b'
down_revision = 'ed9dabb3e8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('value', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
